apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    address-pools:
      - name: test-network
        protocol: layer2
        addresses:
          - 192.168.49.100-192.168.49.200
