# Criação do Namespace para o MetalLB
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
# Configuração do MetalLB com protocolo Layer 2
apiVersion: metallb.io/v1beta1
kind: Config
metadata:
  name: config
  namespace: metallb-system
spec:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 192.168.1.240-192.168.1.250  # Faixa de IPs que o MetalLB usará
