# Create the namespace and install MetalLB
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
# MetalLB configuration with Layer 2 protocol
apiVersion: metallb.io/v1beta1
kind: Config
metadata:
  name: config
  namespace: metallb-system
spec:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 192.168.1.240-192.168.1.250  # Replace with the IP range you want to use

---
# MetalLB Controller Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb-controller
  template:
    metadata:
      labels:
        app: metallb-controller
    spec:
      containers:
      - name: controller
        image: metallb/controller:v0.14.9
        ports:
        - containerPort: 7472
        volumeMounts:
        - name: config
          mountPath: /etc/metallb
      volumes:
      - name: config
        configMap:
          name: metallb-config

---
# MetalLB Speaker DaemonSet configuration
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb-speaker
  template:
    metadata:
      labels:
        app: metallb-speaker
    spec:
      containers:
      - name: speaker
        image: metallb/speaker:v0.14.9
        ports:
        - containerPort: 7472
        volumeMounts:
        - name: config
          mountPath: /etc/metallb
      volumes:
      - name: config
        configMap:
          name: metallb-config
