apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-network
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise-test-network-pool1
  namespace: metallb-system
spec:
  ipAddressPools:
  - test-network
